import type { Order,SimulationState,Action } from '../domain/simulation';
import type { Dispatch } from 'react';
import { Icon } from './Icon';
import { money } from '../domain/products';
const labels={pending:'Ausstehend',running:'Läuft',success:'Erfolgreich',failed:'Fehlgeschlagen'};
const time=(value:string)=>new Date(value).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit',second:'2-digit'});
export function WorkflowPanel({state,dispatch,selected,setSelected}:{state:SimulationState;dispatch:Dispatch<Action>;selected:string|null;setSelected:(id:string|null)=>void}) {
  const order:Order|undefined=state.orders.find(o=>o.id===selected)??state.orders.at(-1);
  const success=order?.steps.filter(s=>s.status==='success').length??0;
  return <section className="workflow-panel" aria-label="Live-Automationsworkflow">
    <div className="panel-heading"><div><p className="eyebrow">AUTOMATION ENGINE</p><h2>Vom Kauf zum Ereignis.</h2></div><span className={`engine-light ${state.orders.some(o=>o.status==='processing')?'working':''}`} title="Lokaler Simulator"/></div>
    <div className="workflow-summary"><span><Icon name="activity" size={16}/>{order?order.id:'Bereit für den ersten Kauf'}</span><span className={`badge ${order?.status==='failed'?'danger':''}`}>{order?order.status==='completed'?'Abgeschlossen':order.status==='failed'?'Test / Fehler':order.status==='queued'?'In Warteschlange':'Wird verarbeitet':'Live'}</span></div>
    {state.orders.length>0&&<><label className="order-select">Bestellung ansehen<select aria-label="Bestellung auswählen" value={order?.id??''} onChange={e=>setSelected(e.target.value)}>{state.orders.slice().reverse().map(o=><option key={o.id} value={o.id}>{o.id} · {o.source==='manual'?'Manuell':'Kund:in'} · {money(o.total)} {o.status==='failed'?'· Fehler':''}</option>)}</select></label><button className={`follow-live ${selected===null?'active':''}`} aria-pressed={selected===null} onClick={()=>setSelected(null)}><Icon name="activity" size={13}/>{selected===null?'Neueste Bestellung wird live angezeigt':'Neuester Bestellung live folgen'}</button></>}
    {!order?<div className="workflow-empty"><div className="workflow-illustration"><Icon name="cart"/><span/><Icon name="box"/><span/><Icon name="check"/></div><h3>Ein Einkauf. Ein sichtbarer Workflow.</h3><p>Wähle ein Produkt im Laden und löse einen Demo-Kauf aus. Oder beobachte die animierten Kund:innen.</p><div className="demo-tip"><Icon name="warning" size={18}/><span>Erster Test: <strong>1 × Kesselchips</strong> kaufen. Der Bestand sinkt von 4 auf 3 und löst eine Lagerwarnung aus.</span></div><ol className="idle-steps"><li>Bestellung erzeugen</li><li>Bestand prüfen & aktualisieren</li><li>Warnung simulieren & abschließen</li></ol></div>:<>
      <div className="workflow-progress"><span style={{width:`${success/order.steps.length*100}%`}}/></div>
      <ol className="event-timeline">{order.steps.map((event,index)=><li key={event.name} className={`event ${event.status}`}><div className="event-dot">{event.status==='success'?<Icon name="check" size={14}/>:event.status==='failed'?<span>!</span>:<span>{index+1}</span>}</div><div className="event-content"><div className="event-top"><code>{event.name}</code><span className="event-status">{labels[event.status]}</span></div><p>{event.description}</p><time dateTime={event.timestamp??order.createdAt}>{event.timestamp?time(event.timestamp):'— · noch ausstehend'}</time></div></li>)}</ol>
      <div className="order-result"><span>{order.source==='manual'?'Manueller Einkauf':'Animierte Demo-Kund:in'} · {money(order.total)}</span><span>Versuch {order.attempts}</span></div>
      {order.status==='failed'&&<div className="retry-box" role="alert"><p>{order.inventoryApplied?'Bestand bereits gebucht. Retry setzt den Abschluss fort, ohne erneut abzubuchen.':'Bestandsprüfung fehlgeschlagen. Es wurde nichts abgebucht.'}</p><button className="button primary" onClick={()=>dispatch({type:'order.retry',orderId:order.id,now:Date.now()})}><Icon name="reset" size={16}/>Erneut versuchen</button></div>}
      {order.status==='completed'&&<div className="success-note"><Icon name="check" size={16}/>Demo-Prozess erfolgreich abgeschlossen.</div>}
      {!order.warnings.length&&order.inventoryApplied&&<p className="muted fine">Kein neuer Grenzübertritt: Warn- und Benachrichtigungsschritte sind für diesen Kauf nicht erforderlich.</p>}
    </>}
    <div className="failure-control"><label className="switch-label"><input type="checkbox" checked={state.failEnabled} onChange={e=>dispatch({type:'failure',value:e.target.checked})}/><span className="switch"/><span>Fehler beim Workflow simulieren</span></label><p>Gilt für den nächsten manuellen Kauf. Testfehler beim Abschluss, nach der Bestandsbuchung.</p></div>
    <details className="event-log"><summary>Ereignisprotokoll <span>{state.logs.length}</span></summary><div className="log-list">{state.logs.length?state.logs.slice(0,35).map(l=><div key={l.id} className={`log-entry ${l.status}`}><time>{time(l.timestamp)}</time><div><code>{l.event}</code><small>{l.orderId} · {labels[l.status]}</small><p>{l.description}</p></div></div>):<p>Noch keine Ereignisse. Starte einen Demo-Kauf.</p>}</div></details>
  </section>;
}
