import { lazy,Suspense,useEffect,useState } from 'react';
import { useSimulation } from './hooks/useSimulation';
import { products,productById,money,type Product } from './domain/products';
import { cartTotal } from './domain/simulation';
import { Icon } from './components/Icon';
import { Modal } from './components/Modal';
import { ProductArt } from './components/ProductArt';
import { WorkflowPanel } from './components/WorkflowPanel';
const StoreScene=lazy(()=>import('./scene/StoreScene'));
const disclaimer='Portfolio-Demo – keine echte Bestellung und keine Zahlung';
const features=[
  ['3D-Frontend','Ein begehbarer Laden mit Kamera, Produktinteraktion und animierten Kund:innen.'],
  ['Event-getriebene Verarbeitung','Ein gemeinsamer Ablauf für manuelle Käufe und automatische Kundenereignisse.'],
  ['Warenkorb-Logik','Verfügbare Mengen, Einzelpreise und eine exakte Gesamtsumme in Cent.'],
  ['Lagerverwaltung','Atomare Bestandsbuchung und Warnungen beim Unterschreiten des Mindestbestands.'],
  ['Webhook-Vorbereitung','Ein abgegrenzter Adapter für n8n mit vollständigem lokalem Fallback.'],
  ['Fehlerbehandlung','Ein Testfehler nach der Buchung; Retry ohne doppelte Bestandsreduzierung.'],
  ['Observierbare Workflows','Ereignisse mit Zeitstempeln, Status, Beschreibungen und einem Live-Protokoll.']
];

export default function App() {
  const {state,dispatch,webhook}=useSimulation();
  const [started,setStarted]=useState(window.location.hash==='#/simulation');
  const [selectedProduct,setSelectedProduct]=useState<Product|null>(null),[cartOpen,setCartOpen]=useState(false);
  const [selectedOrder,setSelectedOrder]=useState<string|null>(null),[category,setCategory]=useState('Alle');
  const [chat,setChat]=useState('Hallo, ich bin NOA, dein Demo-Assistent. Frag mich nach unseren Produkten. Meine Antworten entstehen aus den lokalen Produktdaten.');
  const [added,setAdded]=useState(''),[resetOpen,setResetOpen]=useState(false),[aboutOpen,setAboutOpen]=useState(false);
  const count=Object.values(state.cart).reduce((sum,q)=>sum+q,0),completed=state.orders.filter(o=>o.status==='completed').length;
  const latest=state.orders.find(o=>o.id===selectedOrder)??state.orders.at(-1),current=latest?.steps.find(e=>e.status==='running'||e.status==='failed');
  const cartValid=Object.entries(state.cart).every(([id,q])=>q<=state.inventory[id]);
  useEffect(()=>{const onHash=()=>{const active=window.location.hash==='#/simulation';setStarted(active);if(!active)dispatch({type:'running',value:false});};window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash);},[dispatch]);
  useEffect(()=>{
    if(!cartOpen&&selectedOrder&&latest?.status==='queued')document.querySelector('.workflow-panel')?.scrollIntoView({behavior:'smooth',block:window.innerWidth<=700?'start':'nearest'});
  },[cartOpen,selectedOrder,state.orderCounter]);
  function start(){window.location.hash='/simulation';setStarted(true);dispatch({type:'running',value:true});}
  function add(p:Product){dispatch({type:'cart.quantity',productId:p.id,quantity:(state.cart[p.id]??0)+1});setAdded(`${p.name} liegt im Warenkorb.`);}
  function checkout(){setSelectedOrder(`DEMO-${String(state.orderCounter+1).padStart(3,'0')}`);dispatch({type:'cart.checkout',now:Date.now()});setCartOpen(false);}
  function ask(question:string) {
    if(question==='vegan')setChat(`Unsere veganen Snacks: ${products.filter(p=>p.vegan&&['Chips','Schokolade'].includes(p.category)&&state.inventory[p.id]>0).map(p=>`${p.name} (${money(p.price)})`).join(', ')||'momentan ausverkauft'}. Auch Obst und Sauerteigbrot sind pflanzlich. Angaben gelten für unsere Beispieldaten.`);
    if(question==='cheap'){const p=products.filter(p=>state.inventory[p.id]>0).sort((a,b)=>a.price-b.price).slice(0,3);setChat(p.length?`Unsere günstigsten verfügbaren Produkte: ${p.map(p=>`${p.name} für ${money(p.price)}`).join(', ')}. Alle Preise sind Demo-Endpreise.`:'Momentan sind alle Produkte ausverkauft. Setze die Simulation zurück, um das Lager aufzufüllen.');}
    if(question==='low'){const list=products.filter(p=>state.inventory[p.id]<=p.minStock);setChat(list.length?`Diese Produkte solltest du im Blick behalten: ${list.map(p=>`${p.name}: ${state.inventory[p.id]} Stück (Mindestbestand ${p.minStock})`).join('; ')}. Eine Lagerwarnung wird bei einem Kauf ausgelöst, der den Bestand unter den Mindestbestand bringt.`:'Alle Produkte liegen über ihrem Mindestbestand. Unser Demo-Lager ist gut gefüllt.');}
  }
  return <>
    <header className="app-header"><a className="brand" href="#/" aria-label="AI Grocery Store Automation – Projektübersicht"><span className="brand-symbol"><Icon name="store" size={25}/></span><span>AI GROCERY<span className="brand-sub">STORE AUTOMATION</span></span></a><nav aria-label="Hauptnavigation"><button className={!started?'active':''} onClick={()=>{window.location.hash='/';setStarted(false);dispatch({type:'running',value:false});}}>Projekt</button><button className={started?'active':''} onClick={start}>Simulation</button><button onClick={()=>setAboutOpen(true)}>Was es zeigt</button></nav><div className="header-actions"><span className="portfolio-tag">INTERAKTIVE PORTFOLIO-DEMO</span><button className="cart-toggle" onClick={()=>setCartOpen(true)} aria-label={`Warenkorb öffnen, ${count} Artikel`}><Icon name="cart"/><span>Warenkorb</span><b>{count}</b></button></div></header>
    <main className={`app-main ${!started?'landing':''}`}>
      {!started?<section className="intro"><div className="intro-copy"><p className="eyebrow">3D EXPERIENCE / LOCAL AUTOMATION</p><h1>Ein smarter Laden.<br/><span>Ein sichtbarer Datenfluss.</span></h1><p className="intro-description"><strong>AI Grocery Store Automation</strong> zeigt, wie aus einem Einkauf ein Bestellereignis, ein neuer Lagerbestand und eine automatische Warnung werden – live in 3D.</p><div className="intro-buttons"><button className="button primary large" onClick={start}>Simulation starten<Icon name="arrow"/></button><span>Ohne Anmeldung.<br/>Vollständig lokal.</span></div></div><div className="intro-flow"><span className="intro-number">01 → 06</span><p>Vom Produkt<br/>zum fertigen Workflow.</p><div><span>WÄHLEN</span><Icon name="arrow" size={17}/><span>KAUFEN</span><Icon name="arrow" size={17}/><span>AUTOMATISIEREN</span></div></div></section>:<section className="simulation-title"><div><p className="eyebrow">LIVE DEMO / EVENT-DRIVEN STORE</p><h1>AI Grocery Store <span>Automation</span></h1><p>Produkte entdecken. Demo-Kauf auslösen. Den Datenfluss live verfolgen.</p></div><span className="demo-label"><Icon name="layers" size={16}/>100 % Simulation</span></section>}
      <section className="dashboard-strip" aria-label="Automationsdashboard"><div className="metric"><span className="metric-icon"><Icon name="cart"/></span><div><span>Bestellungen erstellt</span><strong>{state.orders.length}<small>{completed} abgeschlossen</small></strong></div></div><div className="metric"><span className="metric-icon"><Icon name="box"/></span><div><span>Artikel im Lager</span><strong>{Object.values(state.inventory).reduce((s,n)=>s+n,0)}<small>{products.length} Produkte</small></strong></div></div><div className="metric"><span className={`metric-icon ${state.warnings.length?'amber':''}`}><Icon name="warning"/></span><div><span>Lagerwarnungen</span><strong>{state.warnings.length}<small>bei Grenzübertritt</small></strong></div></div><div className="metric webhook-metric"><span className="metric-icon"><Icon name="activity"/></span><div><span>Webhook-Modus</span><strong className="mode-name">{webhook.mode==='connected'?'Webhook verbunden':'Lokale Demo-Verarbeitung'}</strong><small>{webhook.mode==='connected'?'Demo-Payload übertragen':'Kein externer Dienst erforderlich'}</small></div></div></section>
      <div className="workspace-grid"><div className="store-column"><section className="store-panel" aria-label="Interaktiver Laden"><div className="store-toolbar"><span className={`simulation-status ${state.running?'running':''}`}><i/>{state.running?'Simulation läuft':started?'Kund:innen pausiert':'Bereit zum Start'}<b>{state.speed}×</b><time>{Math.floor(state.elapsed/60).toString().padStart(2,'0')}:{Math.floor(state.elapsed%60).toString().padStart(2,'0')}</time></span><div className="simulation-controls"><button className="icon-button" aria-label={state.running?'Kund:innen pausieren':'Kund:innen starten'} title={state.running?'Kund:innen pausieren':'Kund:innen starten'} onClick={()=>{if(!started)start();else dispatch({type:'running',value:!state.running});}}><Icon name={state.running?'pause':'play'} size={18}/></button><button className={`control-button ${state.speed===4?'active':''}`} aria-label={state.speed===4?'Normales Tempo':'Simulation beschleunigen'} title={state.speed===4?'Normales Tempo':'Simulation beschleunigen'} onClick={()=>dispatch({type:'speed'})}><Icon name="fast" size={16}/><span>{state.speed===4?'Normales Tempo':'Simulation beschleunigen'}</span></button><button className="icon-button" aria-label="Simulation zurücksetzen" title="Simulation zurücksetzen" onClick={()=>setResetOpen(true)}><Icon name="reset" size={18}/></button></div></div>
        <Suspense fallback={<div className="scene-loading"><span className="spinner"/>3D-Laden wird geladen …</div>}><StoreScene state={state} onSelect={p=>{setSelectedProduct(p);setAdded('');}}/></Suspense>
        <div className="scene-caption"><span><Icon name="store" size={16}/>Eigene 3D-Geometrie · neutrale Beispielprodukte</span><span>{state.customers.length} Kund:innen im Laden</span></div>
      </section>
      <section className="products-panel" aria-label="Produkte im Laden"><div className="section-heading"><div><p className="eyebrow">PRODUKTAUSWAHL</p><h2>Frisch, knusprig, verfügbar.</h2></div><span>{products.length} Produkte</span></div><div className="category-tabs" aria-label="Produktkategorie">{['Alle','Chips','Schokolade','Getränke','Obst','Backwaren'].map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)} aria-pressed={category===c}>{c}</button>)}</div><div className="product-grid">{products.filter(p=>category==='Alle'||p.category===category).map(p=><button className="product-card" key={p.id} onClick={()=>{setSelectedProduct(p);setAdded('');}} aria-label={`${p.name} – ${money(p.price)} – Details öffnen`}><ProductArt product={p}/><div><span className="product-category">{p.category} · {p.size}</span><h3>{p.name}</h3><div className="product-card-bottom"><strong>{money(p.price)}</strong><span className={state.inventory[p.id]<p.minStock?'stock low':'stock'}>{state.inventory[p.id]} auf Lager</span></div></div><span className="card-plus"><Icon name="plus" size={16}/></span></button>)}</div></section>
      <section className="robot-chat" aria-label="Demo-Assistent NOA"><div className="robot-chat-head"><span className="robot-avatar"><Icon name="robot" size={27}/></span><div><h2>Frag NOA.</h2><p>Regelbasierter Demo-Assistent · keine KI-API</p></div><span className="badge">Lokale Daten</span></div><p className="chat-answer" aria-live="polite">{chat}</p><div className="quick-questions"><button onClick={()=>ask('vegan')}>Welche Snacks sind vegan?</button><button onClick={()=>ask('cheap')}>Was ist gerade günstig?</button><button onClick={()=>ask('low')}>Was ist fast ausverkauft?</button></div></section>
      </div><aside className="automation-column" id="workflow-anchor"><WorkflowPanel state={state} dispatch={dispatch} selected={selectedOrder} setSelected={setSelectedOrder}/>
      <section className="inventory-panel" aria-label="Aktueller Lagerbestand"><div className="section-heading"><div><p className="eyebrow">INVENTORY MONITOR</p><h2>Lager im Blick.</h2></div><Icon name="box"/></div><div className="inventory-legend"><span><i className="green-dot"/>Verfügbar</span><span><i className="amber-dot"/>Unter Minimum</span></div><div className="inventory-table"><div className="inventory-row table-head"><span>Produkt</span><span>Bestand / Min.</span></div>{products.map(p=><div className={`inventory-row ${state.inventory[p.id]<p.minStock?'low':''}`} key={p.id}><span><i style={{background:p.color}}/>{p.shortName}</span><span><strong>{state.inventory[p.id]}</strong> / {p.minStock}{state.inventory[p.id]<p.minStock&&<Icon name="warning" size={14}/>}</span></div>)}</div>{state.warnings.length>0&&<div className="stock-alert" role="status"><Icon name="warning" size={18}/><div><strong>Lagerwarnung ausgelöst</strong><p>{productById[state.warnings.at(-1)!.productId].name} · {state.warnings.at(-1)!.remaining} Stück nach {state.warnings.at(-1)!.orderId}. E-Mail-/Slack-Hinweis wird im Workflow simuliert.</p></div></div>}<p className="webhook-note">{webhook.description}</p></section></aside></div>
      <section className="project-shows" id="project-shows"><div><p className="eyebrow">PORTFOLIO / ENGINEERING</p><h2>Was dieses Projekt zeigt.</h2><p>Die 3D-Szene macht den Einkauf erlebbar.<br/>Der lokale Simulator macht die Automation nachvollziehbar.</p></div><div className="feature-grid">{features.map(([title,text],i)=><div key={title}><span>{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{text}</p></div>)}</div></section>
      <footer><span>AI Grocery Store Automation · Portfolio-Projekt</span><span>{disclaimer}</span></footer>
    </main>
    <div className="screen-reader-status" role="status">{current?`${latest?.id}: ${current.name} – ${current.status==='failed'?'fehlgeschlagen':'läuft'}`:latest?.status==='completed'?`${latest.id}: erfolgreich abgeschlossen`:''}</div>
    {state.message&&<div className="toast" role="alert"><span>{state.message}</span><button aria-label="Hinweis schließen" onClick={()=>dispatch({type:'message.clear'})}><Icon name="close" size={16}/></button></div>}
    {selectedProduct&&<Modal title="Produktdetails" onClose={()=>setSelectedProduct(null)} className="product-modal"><ProductArt product={selectedProduct}/><div className="product-detail"><p className="eyebrow">{selectedProduct.category} · {selectedProduct.size}</p><h2>{selectedProduct.name}</h2><p className="detail-description">{selectedProduct.description}</p><div className="detail-price"><strong>{money(selectedProduct.price)}</strong><span>{selectedProduct.vegan?'Pflanzlich / vegan':'Enthält Milch'}</span></div><div className="detail-stock"><span>Lagerbestand<strong>{state.inventory[selectedProduct.id]} Stück</strong></span><span>Mindestbestand<strong>{selectedProduct.minStock} Stück</strong></span></div>{state.inventory[selectedProduct.id]<selectedProduct.minStock&&<p className="low-stock-note">Niedriger Bestand – eine Lagerwarnung ist im Dashboard sichtbar.</p>}{selectedProduct.id==='chips'&&state.inventory.chips===4&&<p className="demo-tip">Demo-Tipp: Mit 1 Packung fällt der Bestand unter das Minimum und zeigt alle sechs Workflow-Schritte.</p>}<button className="button primary full" disabled={(state.cart[selectedProduct.id]??0)>=state.inventory[selectedProduct.id]} onClick={()=>add(selectedProduct)}><Icon name="plus" size={18}/>{state.inventory[selectedProduct.id]===0?'Ausverkauft':'In Warenkorb'}</button>{added&&<div className="added-message" role="status"><Icon name="check" size={16}/>{added}</div>}<button className="button secondary full" onClick={()=>{setSelectedProduct(null);setCartOpen(true);}}>Warenkorb ansehen ({count})<Icon name="arrow" size={17}/></button><p className="fine muted">{disclaimer}</p></div></Modal>}
    {cartOpen&&<Modal title="Warenkorb" onClose={()=>setCartOpen(false)} className="cart-modal"><p className="eyebrow">DEIN DEMO-EINKAUF</p><h2>Warenkorb <span>({count})</span></h2><p className="muted">Wähle Mengen und löse den lokalen Workflow aus.</p>{count?<><div className="cart-lines">{Object.entries(state.cart).map(([id,quantity])=>{const p=productById[id];return <article className="cart-line" key={id}><ProductArt product={p} small/><div><h3>{p.name}</h3><p>{money(p.price)} / Stück · {p.size}</p><div className="quantity"><button aria-label={`${p.name}: Menge verringern`} onClick={()=>dispatch({type:'cart.quantity',productId:id,quantity:quantity-1})}><Icon name="minus" size={15}/></button><output aria-label={`${p.name}: Menge`}>{quantity}</output><button aria-label={`${p.name}: Menge erhöhen`} disabled={quantity>=state.inventory[id]} onClick={()=>dispatch({type:'cart.quantity',productId:id,quantity:quantity+1})}><Icon name="plus" size={15}/></button></div>{quantity>state.inventory[id]&&<p className="stock-error">Nur noch {state.inventory[id]} verfügbar. Bitte Menge reduzieren.</p>}</div><div className="cart-line-right"><strong>{money(p.price*quantity)}</strong><button className="icon-button" aria-label={`${p.name} entfernen`} onClick={()=>dispatch({type:'cart.quantity',productId:id,quantity:0})}><Icon name="trash" size={17}/></button></div></article>;})}</div><div className="cart-total"><span>Gesamtsumme</span><strong>{money(cartTotal(state.cart))}</strong></div><p className="demo-disclaimer"><Icon name="layers" size={18}/>{disclaimer}</p><button className="button primary full large" disabled={!cartValid} onClick={checkout}>Demo-Kauf auslösen<Icon name="arrow"/></button><p className="fine muted">{state.failEnabled?'Testfehler aktiv: Der Workflow stoppt beim Abschluss. „Erneut versuchen“ setzt ihn sicher fort.':'Die Bestandsprüfung startet nach dem Klick. Alle Ereignisse erscheinen live im Automationspanel.'}</p></>:<div className="cart-empty"><Icon name="cart" size={45}/><h3>Dein Warenkorb ist noch leer.</h3><p>Klicke auf ein Produkt im 3D-Laden oder in der Produktliste.</p><button className="button primary" onClick={()=>setCartOpen(false)}>Produkte entdecken<Icon name="arrow" size={17}/></button></div>}</Modal>}
    {resetOpen&&<Modal title="Simulation zurücksetzen" onClose={()=>setResetOpen(false)} className="reset-modal"><span className="reset-icon"><Icon name="reset" size={30}/></span><h2>Alles auf Anfang?</h2><p>Bestände, Warenkorb, Demo-Bestellungen, Warnungen und Ereignisse werden auf die Ausgangswerte gesetzt.</p><button className="button primary full" onClick={()=>{dispatch({type:'reset',now:Date.now()});setSelectedOrder(null);setResetOpen(false);setChat('Das Demo-Lager ist wieder aufgefüllt. Ich bin bereit für deine Fragen.');}}>Simulation zurücksetzen</button><button className="button secondary full" onClick={()=>setResetOpen(false)}>Weiter ansehen</button></Modal>}
    {aboutOpen&&<Modal title="Was dieses Projekt zeigt" onClose={()=>setAboutOpen(false)} className="about-modal"><p className="eyebrow">AI GROCERY STORE AUTOMATION</p><h2>Was dieses Projekt zeigt.</h2><p>Eine interaktive 3D-Oberfläche, verbunden mit einem korrekten, nachvollziehbaren lokalen Automationsprozess.</p><div className="about-list">{features.map(([title,text])=><article key={title}><Icon name="check" size={18}/><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><p className="demo-disclaimer">{disclaimer}. Keine personenbezogenen Daten, keine externe KI und keine echten Benachrichtigungen.</p></Modal>}
  </>;
}
